### ISSUE TITLE
Volume 100%

### ISSUE THREAD

**Issue by brandon-claps** [hikirsch/htd_mc-home-assistant#5] opened 2022-04-16 03:27 UTC
When trying to set the volume to 100% through home assistant it doesn’t work. If I set the volume to max through the HTD app, the HTD plugin in HA shows 0

**Comment by hikirsch** [comment] 2024-04-20 14:49
Are you still experiencing this problem? I am unable to reproduce this and I have not had any other reports of this.

**Comment by brandon-claps** [comment] 2024-04-20 17:52
> Are you still experiencing this problem? I am unable to reproduce this and I have not had any other reports of this.

Yes, I can still reproduce it. When the volume is set to 100% in HA, the HTD app shows its set to 59 (max is 60). If I try and change the volume to 60 in HTD, I'm then unable to adjust the volume in HA.

**Comment by hikirsch** [comment] 2024-04-20 18:08
yea i can reproduce this actually

**Comment by brandon-claps** [comment] 2024-04-26 13:46
> yea i can reproduce this actually

Great, let me know if you want me to test anything

**Comment by hikirsch** [comment] 2024-06-16 21:53
Hey @S10XtremeNLow -

Thanks for being patient. I completely rewrote the python client. I think this should be much better now. The way that this device switches volume though is really sucky. It can only tick 1 volume db at a time. So it takes a few seconds to get to the new desired volume. If there's a volume change in progress on a zone, any volume changes will be ignored until it's done with the initial request.

If you can give it a go and give me your first impressions that would be really appreciated. If you installed this via HACS, you should be able to choose a new preview version of v1.2.0-BETA.1. 

Please give it a shot and let me know how that goes.

Thanks.

**Comment by brandon-claps** [comment] 2024-06-16 21:54
> Hey @S10XtremeNLow -
> 
> Thanks for being patient. I completely rewrote the python client. I think this should be much better now. The way that this device switches volume though is really sucky. It can only tick 1 volume db at a time. So it takes a few seconds to get to the new desired volume. If there's a volume change in progress on a zone, any volume changes will be ignored until it's done with the initial request.
> 
> If you can give it a go and give me your first impressions that would be really appreciated. If you installed this via HACS, you should be able to choose a new preview version of v1.2.0-BETA.1.
> 
> Please give it a shot and let me know how that goes.
> 
> Thanks.

What a Father’s Day gift! Thanks, I’ll let you know if I see any issues.

**Comment by brandon-claps** [comment] 2024-06-17 01:47
> Hey @S10XtremeNLow -
> 
> Thanks for being patient. I completely rewrote the python client. I think this should be much better now. The way that this device switches volume though is really sucky. It can only tick 1 volume db at a time. So it takes a few seconds to get to the new desired volume. If there's a volume change in progress on a zone, any volume changes will be ignored until it's done with the initial request.
> 
> If you can give it a go and give me your first impressions that would be really appreciated. If you installed this via HACS, you should be able to choose a new preview version of v1.2.0-BETA.1.
> 
> Please give it a shot and let me know how that goes.
> 
> Thanks.

Looks like the release hasn’t been published to GitHub. I get a 404 when trying to install on HACS. 404 on this URL. https://github.com/hikirsch/htd_mc-home-assistant/releases/download/v1.2.0-BETA.1/htd_mc.zip

Want me to install manually?

**Comment by hikirsch** [comment] 2024-06-17 16:11
Oh, sorry, I didn't upload the files to the release, you can download the files from the [branch](https://github.com/hikirsch/htd_mc-home-assistant/tree/ask.new-client) directly or use HACS and pick this as a new pre-release. I can upload the files in the release later.

**Comment by brandon-claps** [comment] 2024-06-17 16:20
> Oh, sorry, I didn't upload the files to the release, you can download the files from the [branch](https://github.com/hikirsch/htd_mc-home-assistant/tree/ask.new-client) directly or use HACS and pick this as a new pre-release. I can upload the files in the release later.

I’m choosing the branch from HACS. See attached photo
![IMG_0842](https://github.com/hikirsch/htd_mc-home-assistant/assets/24376289/d7cf505a-68f6-4cd9-9b0c-f02ae6cd5caf)

**Comment by hikirsch** [comment] 2024-06-17 19:57
ok can you try again? sorry about that.

**Comment by brandon-claps** [comment] 2024-06-17 20:01
Installed this time but getting “Setup failed for 'htd_mc': Integration not found. “

looking at the folder directory, looks like htd_mc is inside a htd_mc folder along with a MACOSX directory

**Comment by hikirsch** [comment] 2024-06-17 21:09
not my day.... can you try again?

**Comment by brandon-claps** [comment] 2024-06-17 21:21
Any requirements change for configuration? Getting this error now: Component error: htd_mc - No module named 'htd_mc_client'

**Comment by hikirsch** [comment] 2024-06-17 21:57
definitely not my day, can you try again? there's now a beta.2. no there are no config updates required.

**Comment by brandon-claps** [comment] 2024-06-17 22:13
It sets up now. Looks like it can’t get current power state of a zone. Had a zone on and it didn’t show on. I can turn on a zone but it doesn’t show the new state so can’t turn off the zone.

**Comment by hikirsch** [comment] 2024-06-17 23:33
ok at least progress, yes this I'm aware of. does it eventually stabilize? are you able to set the volume properly?

**Comment by brandon-claps** [comment] 2024-06-17 23:48
Kind of. I had on state (they were all on in HA) but none were actually turned on. The volume does go to max and minimum now. It does seem like it locks up when changing the volume. For example if I’m at 5 and go to 80 on accident and try to change it to 40, it doesn’t respond. 

Getting closer!

**Comment by hikirsch** [comment] 2024-06-18 01:32
can i ask you to reach out to me on Discord?

**Comment by S10XtremeNLow** [comment] 2024-06-18 10:19
Sure, my name is same as on here

Brandon

**Comment by hikirsch** [comment] 2024-07-12 01:43
hey @S10XtremeNLow thanks for your help with this! i released v1.2.0 with the new options and as a final. 

going to close this. please report further issues here!

**Closed as completed by hikirsch** 2024-07-12 01:43 UTC
